AWSTemplateFormatVersion: "2010-09-09"
Description: "MarketBrewer SEO Platform v1.0.0 - Automated EC2 Deployment"

Parameters:
  EnvironmentName:
    Type: String
    Default: production
    AllowedValues: [development, staging, production]
    Description: Environment name for tagging and configuration

  InstanceType:
    Type: String
    Default: t3.large
    AllowedValues: [t3.large, t3.xlarge]
    Description: EC2 instance type (t3.large recommended for v1.0)

  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of existing EC2 key pair for SSH access

  SSHAccessCIDR:
    Type: String
    Default: 0.0.0.0/0
    Description: CIDR block allowed to SSH (restrict to your IP for security)

  EnableAutoStop:
    Type: String
    Default: "true"
    AllowedValues: ["true", "false"]
    Description: Enable auto-stop script when idle (saves money!)

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Environment Configuration
        Parameters:
          - EnvironmentName
          - InstanceType
          - KeyPairName
          - SSHAccessCIDR
          - EnableAutoStop

Resources:
  # IAM Role for EC2 instance (permissions to stop itself, access CloudWatch, etc.)
  MarketBrewerEC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy"
      Policies:
        - PolicyName: EC2SelfManagement
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ec2:StopInstances"
                  - "ec2:DescribeInstances"
                Resource: !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/*"
                Condition:
                  StringEquals:
                    "ec2:InstanceType": !Ref InstanceType
      Tags:
        - Key: Name
          Value: !Sub "marketbrewer-${EnvironmentName}-role"
        - Key: Environment
          Value: !Ref EnvironmentName

  MarketBrewerEC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref MarketBrewerEC2Role

  # Security Group
  MarketBrewerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for MarketBrewer SEO Platform
      SecurityGroupIngress:
        # SSH
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHAccessCIDR
          Description: SSH access

        # API Server
        - IpProtocol: tcp
          FromPort: 3001
          ToPort: 3001
          CidrIp: 0.0.0.0/0
          Description: MarketBrewer API server

        # Dashboard (if hosted on EC2)
        - IpProtocol: tcp
          FromPort: 3002
          ToPort: 3002
          CidrIp: 0.0.0.0/0
          Description: Dashboard (optional)

        # Ollama (internal only)
        - IpProtocol: tcp
          FromPort: 11434
          ToPort: 11434
          CidrIp: 127.0.0.1/32
          Description: Ollama (local only)

      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic

      Tags:
        - Key: Name
          Value: !Sub "marketbrewer-${EnvironmentName}-sg"
        - Key: Environment
          Value: !Ref EnvironmentName

  # EC2 Instance
  MarketBrewerEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c55b159cbfafe1f0 # Ubuntu 22.04 LTS
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyPairName
      IamInstanceProfile: !Ref MarketBrewerEC2InstanceProfile
      SecurityGroupIds:
        - !Ref MarketBrewerSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 50
            VolumeType: gp3
            DeleteOnTermination: true

      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e

          # Log all output
          exec > /var/log/marketbrewer-setup.log 2>&1
          echo "=== MarketBrewer Setup Started: $(date) ==="

          # Update system
          apt-get update
          apt-get upgrade -y

          # Install required tools
          apt-get install -y \
            curl \
            wget \
            git \
            build-essential \
            python3 \
            htop \
            jq \
            unzip

          # Install Node.js 18 LTS
          echo "Installing Node.js 18 LTS..."
          curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
          apt-get install -y nodejs

          echo "Node.js version: $(node --version)"
          echo "npm version: $(npm --version)"

          # Install Ollama
          echo "Installing Ollama..."
          curl -fsSL https://ollama.ai/install.sh | sh

          # Start Ollama service
          systemctl start ollama
          systemctl enable ollama

          # Wait for Ollama to be ready
          echo "Waiting for Ollama to start..."
          sleep 5

          # Pull llama3.2 model (takes ~10 minutes)
          echo "Pulling llama3.2 model (this takes ~10 minutes)..."
          ollama pull llama3.2

          # Create application directory
          echo "Setting up application directory..."
          mkdir -p /var/www/marketbrewer-seo-platform
          mkdir -p /var/lib/marketbrewer/backups
          chown -R ubuntu:ubuntu /var/www/marketbrewer-seo-platform
          chown -R ubuntu:ubuntu /var/lib/marketbrewer

          # Clone repository
          echo "Cloning repository..."
          cd /var/www/marketbrewer-seo-platform
          sudo -u ubuntu git clone https://github.com/dmv7zero3/marketbrewer-seo-platform.git .

          # Install dependencies as ubuntu user
          echo "Installing npm dependencies..."
          sudo -u ubuntu npm install

          # Create .env file
          echo "Creating environment configuration..."
          sudo -u ubuntu cp .env.example .env

          # Update critical env vars
          sed -i 's/NODE_ENV=.*/NODE_ENV=production/' /var/www/marketbrewer-seo-platform/.env
          sed -i 's|DATABASE_PATH=.*|DATABASE_PATH=/var/lib/marketbrewer/seo-platform.db|' /var/www/marketbrewer-seo-platform/.env

          # Build for production
          echo "Building application..."
          sudo -u ubuntu npm run build:all

          # Copy systemd service files
          echo "Installing systemd services..."
          cp /var/www/marketbrewer-seo-platform/systemd/seo-api.service /etc/systemd/system/
          cp /var/www/marketbrewer-seo-platform/systemd/seo-worker.service /etc/systemd/system/

          # Reload systemd
          systemctl daemon-reload

          # Enable services (but don't start yet - let database initialize)
          systemctl enable seo-api seo-worker

          # Install auto-stop script (if enabled)
          if [ "${EnableAutoStop}" == "true" ]; then
            echo "Installing auto-stop script..."
            cat > /usr/local/bin/ec2-auto-shutdown.sh << 'EOFSCRIPT'
          #!/bin/bash
          INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
          IDLE_THRESHOLD_MINUTES=30
          CPU_THRESHOLD=5
          CHECK_INTERVAL_SECONDS=60
          IDLE_COUNTER=0

          while true; do
            CPU_USAGE=$(top -bn1 | grep "Cpu(s)" | awk '{print $2}' | cut -d'%' -f1 | cut -d'.' -f1)
            
            if [ "$CPU_USAGE" -lt "$CPU_THRESHOLD" ]; then
              IDLE_COUNTER=$((IDLE_COUNTER + 1))
              IDLE_MINUTES=$((IDLE_COUNTER * CHECK_INTERVAL_SECONDS / 60))
              
              if [ "$IDLE_MINUTES" -ge "$IDLE_THRESHOLD_MINUTES" ]; then
                echo "[$(date)] CPU idle for $IDLE_MINUTES minutes. Stopping instance..."
                aws ec2 stop-instances --instance-ids "$INSTANCE_ID" --region ${AWS::Region}
                exit 0
              fi
            else
              IDLE_COUNTER=0
            fi
            
            sleep "$CHECK_INTERVAL_SECONDS"
          done
          EOFSCRIPT
            chmod +x /usr/local/bin/ec2-auto-shutdown.sh
            
            # Run auto-stop in background
            nohup /usr/local/bin/ec2-auto-shutdown.sh > /var/log/ec2-auto-shutdown.log 2>&1 &
          fi

          # Start services
          echo "Starting services..."
          systemctl start seo-api
          sleep 5
          systemctl start seo-worker

          # Setup CloudWatch agent (optional monitoring)
          echo "Setting up CloudWatch monitoring..."
          apt-get install -y amazon-cloudwatch-agent

          # Create backup cron job
          echo "Setting up daily backups..."
          cat > /usr/local/bin/backup-marketbrewer.sh << 'EOFBACKUP'
          #!/bin/bash
          BACKUP_DIR="/var/lib/marketbrewer/backups"
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          cp /var/lib/marketbrewer/seo-platform.db $BACKUP_DIR/seo-platform.db.$TIMESTAMP.backup
          echo "Backup created: seo-platform.db.$TIMESTAMP.backup"
          find $BACKUP_DIR -name "*.backup" -mtime +7 -delete
          EOFBACKUP
          chmod +x /usr/local/bin/backup-marketbrewer.sh

          # Add to crontab (2am UTC daily)
          echo "0 2 * * * root /usr/local/bin/backup-marketbrewer.sh" >> /etc/cron.d/marketbrewer-backup

          echo "=== MarketBrewer Setup Completed: $(date) ==="
          echo "API Server URL: http://$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4):3001"
          echo "Check logs: tail -f /var/log/marketbrewer-setup.log"

      Monitoring: true
      Tags:
        - Key: Name
          Value: !Sub "marketbrewer-${EnvironmentName}"
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: marketbrewer-seo-platform
        - Key: Version
          Value: "1.0.0"

  # Elastic IP for consistent access
  MarketBrewerEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref MarketBrewerEC2Instance
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub "marketbrewer-${EnvironmentName}-eip"

  # CloudWatch Alarm for billing (optional but recommended)
  BillingAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "marketbrewer-${EnvironmentName}-billing-alert"
      AlarmDescription: Alert if estimated charges exceed budget
      MetricName: EstimatedCharges
      Namespace: AWS/Billing
      Statistic: Maximum
      Period: 86400
      EvaluationPeriods: 1
      Threshold: 30
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:marketbrewer-alerts"

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref MarketBrewerEC2Instance
    Export:
      Name: !Sub "${AWS::StackName}-InstanceId"

  InstancePublicIP:
    Description: Public IP address of the EC2 instance
    Value: !Ref MarketBrewerEIP
    Export:
      Name: !Sub "${AWS::StackName}-PublicIP"

  APIEndpoint:
    Description: MarketBrewer API endpoint
    Value: !Sub "http://${MarketBrewerEIP}:3001"
    Export:
      Name: !Sub "${AWS::StackName}-APIEndpoint"

  DashboardEndpoint:
    Description: Dashboard endpoint (if hosted on EC2)
    Value: !Sub "http://${MarketBrewerEIP}:3002"
    Export:
      Name: !Sub "${AWS::StackName}-DashboardEndpoint"

  SecurityGroupId:
    Description: Security Group ID
    Value: !Ref MarketBrewerSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-SecurityGroup"

  SSHCommand:
    Description: SSH command to connect to instance
    Value: !Sub "ssh -i /path/to/key.pem ubuntu@${MarketBrewerEIP}"

  SetupLogLocation:
    Description: Location of setup log (SSH in and run)
    Value: tail -f /var/log/marketbrewer-setup.log

  CostOptimizationTip:
    Description: Save money by stopping the instance when not in use
    Value: !Sub |
      Stop: aws ec2 stop-instances --instance-ids ${MarketBrewerEC2Instance} --region ${AWS::Region}
      Start: aws ec2 start-instances --instance-ids ${MarketBrewerEC2Instance} --region ${AWS::Region}
      Cost: ~$20/month (8h/day) + $2.50 storage = $22.50/month
